## nzw9314仓库自动定时同步代码 ，教程公众号文章地址  https://mp.weixin.qq.com/s/fcI4vQHD8TNajvTML9g3AA




name: nzw9314-sync
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-nzw9314-QuantumultX

jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync nzw9314-QuantumultX
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/nzw9314/QuantumultX.git"
          source_branch: "main"
          destination_branch: "nzw9314"
          github_token: ${{ secrets.PAT }}
